services:
  - type: web
    name: nave-a-la-deriva-2  # Nombre del servicio en Render
    runtime: python
    region: virginia  # o "us-west", "eu-central", etc.
    branch: main    # Rama de tu repositorio
    buildCommand: pip install -r requirements.txt
    startCommand: uvicorn main:app --host 0.0.0.0 --port 10000
    envVars:
      - key: PYTHON_VERSION
        value: 3.13  
    plan: free  # Plan gratuito